# Generated by Django 3.1.3 on 2020-11-07 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('NA', 'Not available')], max_length=55),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(default='student', max_length=30),
        ),
    ]
