# Generated by Django 3.1.3 on 2020-11-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_auto_20201107_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='book_cover'),
        ),
    ]
