# Generated by Django 3.1.3 on 2020-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_auto_20201107_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('NA', 'Not available')], default='Available', max_length=55),
        ),
    ]
