# Generated by Django 3.1.3 on 2020-11-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_auto_20201107_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
